# VencoPy Tutorial 2

This tutorial aims to give a more in depth overview into the DataParser class and showcases some features that can be customised.

In [17]:
from pathlib import Path

from vencopy.core.dataparsers import parse_data
from vencopy.utils.utils import load_configs, create_output_folders

In [18]:
base_path = Path.cwd().parent
configs = load_configs(base_path)
create_output_folders(configs=configs)
    
# Adapt relative paths in config for tutorials
configs['dev_config']['global']['relative_path']['parse_output'] = Path.cwd().parent / configs['dev_config']['global']['relative_path']['parse_output']
configs['dev_config']['global']['relative_path']['diary_output'] = Path.cwd().parent / configs['dev_config']['global']['relative_path']['diary_output']
configs['dev_config']['global']['relative_path']['grid_output'] = Path.cwd().parent / configs['dev_config']['global']['relative_path']['grid_output']
configs['dev_config']['global']['relative_path']['flex_output'] = Path.cwd().parent / configs['dev_config']['global']['relative_path']['flex_output']
configs['dev_config']['global']['relative_path']['aggregator_output'] = Path.cwd().parent / configs['dev_config']['global']['relative_path']['aggregator_output']
configs['dev_config']['global']['relative_path']['processor_output'] = Path.cwd().parent / configs['dev_config']['global']['relative_path']['processor_output']

# Set reference dataset
datasetID = 'MiD17'

# Modify the localPathConfig file to point to the .csv file in the sampling folder in the tutorials directory where the dataset for the tutorials lies.
configs['user_config']['global']['absolute_path'][datasetID] = Path.cwd() /'data_sampling'

# Similarly we modify the datasetID in the global config file
configs['dev_config']['global']['files'][datasetID]['trips_data_raw'] = datasetID + '.csv'

# We also modify the parseConfig by removing some of the columns that are normally parsed from the MiD, which are not available in our semplified test dataframe
del configs['dev_config']['dataparsers']['data_variables']['household_id']
del configs['dev_config']['dataparsers']['data_variables']['person_id']

## DataParser config file

The DataParser config file defines which variables are to be parsed (i.e. the ones needed to create trip diaries and calculate fleet flexibility) and sets some filtering options, such as the conditions for trips to be included of excluded from the parsing.

<div class="alert alert-block alert-danger"><b>Warning:</b> The list is very long.</div>

In [19]:
configs['dev_config']

{'global': {'relative_path': {'parse_output': WindowsPath('c:/Users/mior_fa/Documents/7_Work/vencopy/vencopy_internal/vencopy/vencopy/output/dataparser'),
   'diary_output': WindowsPath('c:/Users/mior_fa/Documents/7_Work/vencopy/vencopy_internal/vencopy/vencopy/output/diarybuilder'),
   'grid_output': WindowsPath('c:/Users/mior_fa/Documents/7_Work/vencopy/vencopy_internal/vencopy/vencopy/output/gridmodeller'),
   'flex_output': WindowsPath('c:/Users/mior_fa/Documents/7_Work/vencopy/vencopy_internal/vencopy/vencopy/output/flexestimator'),
   'aggregator_output': WindowsPath('c:/Users/mior_fa/Documents/7_Work/vencopy/vencopy_internal/vencopy/vencopy/output/profileaggregator'),
   'processor_output': WindowsPath('c:/Users/mior_fa/Documents/7_Work/vencopy/vencopy_internal/vencopy/vencopy/output/postprocessor'),
   'config': './config/'},
  'files': {'MiD17': {'enrypted_zip_file_B1': 'B1_Standard-DatensatzpaketEncrypted.zip',
    'enrypted_zip_file_B2': 'B2_Regional-DatensatzpaketEncrypted.zip',
    'households_data_raw': 'MiD2017_Regional_Haushalte.csv',
    'persons_data_raw': 'MiD2017_Regional_Personen.csv',
    'trips_data_raw': 'MiD17.csv'},
   'MiD08': {'households_data_raw': 'MiD2008_PUF_Haushalte.dta',
    'person_data_raw': 'MiD2008_PUF_Personen.dta',
    'trips_data_raw': 'MiD2008_PUF_Wege.dta'},
   'KiD': {'trips_data_raw': 'KiD2010-Fahrten-Datei-puf.dta',
    'vehicles_data_raw': 'KiD2010-Fahrzeug-Datei-puf.dta'},
   'VF': {'trips_data_raw': 'MiD2017_Wege.dta',
    'vehicles_data_raw': 'tripDataMergedWVehicleData.csv'}},
  'disk_file_names': {'output_dataparser': 'vencopy_output_dataparser',
   'output_gridmodeller': 'vencopy_output_gridmodeller',
   'output_flexestimator': 'vencopy_output_flexestimator',
   'output_diarybuilder': 'vencopy_output_diarybuilder',
   'output_profileaggregator': 'vencopy_output_profileaggregator',
   'output_postprocessor_annual': 'vencopy_output_postprocessor_annual',
   'output_postprocessor_normalised': 'vencopy_output_postprocessor_normalized'}},
 'dataparsers': {'data_variables': {'dataset': ['MiD08', 'MiD17', 'KiD', 'VF'],
   'is_driver': ['pkw_f', 'W_VM_G', 'NA', 'NA'],
   'vehicle_id': ['NA', 'NA', 'k00', 'A_ID'],
   'vehicle_segment': ['NA', 'NA', 'k01', 'seg_kba_gr'],
   'drivetrain': ['NA', 'NA', 'NA', 'A_ANTRIEB'],
   'household_person_id': ['NA', 'HP_ID_Reg', 'NA', 'HP_ID'],
   'trip_id': ['wid', 'W_ID', 'f00', 'W_ID'],
   'trip_weight': ['w_gew', 'W_GEW', 'k93', 'W_GEW'],
   'trip_scale_factor': ['NA', 'W_HOCH', 'k90', 'W_HOCH'],
   'trip_start_clock': ['st_time', 'W_SZ', 'f04', 'W_SZ'],
   'trip_end_clock': ['en_time', 'W_AZ', 'f10a', 'W_AZ'],
   'trip_purpose': ['w04', 'zweck', 'f07a', 'zweck'],
   'trip_distance': ['wegkm_k', 'wegkm', 'f14', 'wegkm_imp'],
   'travel_time': ['wegmin_k', 'wegmin_imp1', 'f15', 'wegmin_imp1'],
   'trip_start_year': ['stich_j', 'ST_JAHR', 'NA', 'ST_JAHR'],
   'trip_start_month': ['stich_m', 'ST_MONAT', 'NA', 'ST_MONAT'],
   'trip_start_week': ['stichwo', 'ST_WOCHE', 'NA', 'ST_WOCHE'],
   'trip_start_weekday': ['stichtag', 'ST_WOTAG', 'NA', 'ST_WOTAG'],
   'trip_start_hour': ['st_std', 'W_SZS', 'NA', 'W_SZS'],
   'trip_start_minute': ['st_min', 'W_SZM', 'NA', 'W_SZM'],
   'trip_start_date': ['NA', 'NA', 'k22d', 'NA'],
   'trip_end_hour': ['en_std', 'W_AZS', 'NA', 'W_AZS'],
   'trip_end_minute': ['en_min', 'W_AZM', 'NA', 'W_AZM'],
   'trip_end_next_day': ['en_dat', 'W_FOLGETAG', 'NA', 'W_FOLGETAG'],
   'trip_is_intermodal': ['NA', 'weg_intermod', 'NA', 'weg_intermod']},
  'id_variables_names': {'MiD08': 'household_person_id',
   'MiD17': 'household_person_id',
   'KiD': 'vehicle_id',
   'VF': 'household_person_id'},
  'input_data_types': {'MiD17': {'is_driver': 'bool',
    'household_person_id': 'int',
    'trip_id': 'int',
    'trip_weight': 'float',
    'trip_purpose': 'int',
    'trip_distance': 'float',
    'trip_start_year': 'int',
    'trip_start_month': 'int',
    'trip_start_week': 'int',
    'trip_start_weekday': 'int',
    'trip_start_hour': 'int',
    'trip_start_minute': 'int',
    'trip_end_hour': 'int',
    'trip_end_minute': 'int',
    'trip_end_next_day': 'bool',
    'trip_is_intermodal': 'int',
    'weather': 'int',
    'economic_status': 'int',
    'household_type': 'int',
    'hhStatus': 'int',
    'household_person_age': 'int',
    'household_person_job': 'int',
    'bundesland': 'int',
    'area_type': 'int',
    'garage': 'int'},
   'MiD08': {'is_driver': 'bool',
    'household_person_id': 'int',
    'trip_id': 'int',
    'trip_weight': 'float',
    'trip_purpose': 'int',
    'trip_distance': 'float',
    'trip_start_year': 'int',
    'trip_start_month': 'int',
    'trip_start_week': 'int',
    'trip_start_weekday': 'int',
    'trip_start_hour': 'int',
    'trip_start_minute': 'int',
    'trip_end_hour': 'int',
    'trip_end_minute': 'int',
    'trip_end_next_day': 'bool',
    'trip_is_intermodal': 'int'},
   'KiD': {'vehicle_id': 'int',
    'trip_id': 'int',
    'trip_weight': 'float',
    'trip_start_clock': 'str',
    'trip_end_clock': 'str',
    'trip_purpose': 'int',
    'trip_distance': 'float',
    'travel_time': 'int',
    'trip_start_date': 'str',
    'area_type': 'int'},
   'VF': {'is_driver': 'bool',
    'vehicle_id': 'int',
    'drivetrain': 'str',
    'household_person_id': 'int',
    'trip_id': 'int',
    'trip_weight': 'float',
    'trip_purpose': 'int',
    'trip_distance': 'float',
    'trip_start_year': 'int',
    'trip_start_month': 'int',
    'trip_start_week': 'int',
    'trip_start_weekday': 'int',
    'trip_start_hour': 'int',
    'trip_start_minute': 'int',
    'trip_end_hour': 'int',
    'trip_end_minute': 'int',
    'trip_end_next_day': 'bool',
    'trip_is_intermodal': 'int',
    'weather': 'int'}},
  'filters': {'lower_speed_threshold': 10,
   'higher_speed_threshold': 200,
   'MiD08': {'include': {'is_driver': [1]},
    'exclude': {'trip_start_hour': [301],
     'trip_start_minute': [301],
     'trip_end_hour': [301],
     'trip_end_minute': [301],
     'trip_start_clock': ['301:00'],
     'trip_end_clock': ['301:00'],
     'trip_purpose': [97, 98]},
    'greater_than': None,
    'smaller_than': {'trip_distance': [1000]}},
   'MiD17': {'include': {'is_driver': [1]},
    'exclude': {'trip_start_hour': [99, 701],
     'trip_end_hour': [99, 701],
     'trip_start_clock': [' '],
     'trip_end_clock': [' '],
     'trip_purpose': [99],
     'trip_is_intermodal': [1, 703, 708]},
    'greater_than': None,
    'smaller_than': {'trip_distance': [1000]}},
   'KiD': {'include': None,
    'exclude': {'trip_start_date': ['-1'],
     'trip_start_clock': ['-1:-1'],
     'trip_purpose': [-1]},
    'greater_than': None,
    'smaller_than': {'trip_distance': [3000]}},
   'VF': {'include': None,
    'exclude': {'trip_start_hour': [99, 701],
     'trip_end_hour': [99, 701],
     'trip_start_clock': [' '],
     'trip_end_clock': [' '],
     'trip_purpose': [99]},
    'greater_than': None,
    'smaller_than': {'trip_distance': [1000]}}},
  'replacements': {'MiD08': {'trip_start_weekday': {1: 'MON',
     2: 'TUE',
     3: 'WED',
     4: 'THU',
     5: 'FRI',
     6: 'SAT',
     7: 'SUN'},
    'trip_purpose': {1: 'WORK',
     2: 'WORK',
     3: 'SCHOOL',
     4: 'SHOPPING',
     5: 'SHOPPING',
     6: 'LEISURE',
     7: 'LEISURE',
     8: 'HOME',
     9: 'HOME',
     10: 'OTHER',
     11: 'HOME',
     31: 'SCHOOL',
     32: 'SCHOOL',
     99: 'NA'}},
   'MiD17': {'trip_start_weekday': {1: 'MON',
     2: 'TUE',
     3: 'WED',
     4: 'THU',
     5: 'FRI',
     6: 'SAT',
     7: 'SUN'},
    'trip_purpose': {1: 'WORK',
     2: 'WORK',
     3: 'SCHOOL',
     4: 'SHOPPING',
     5: 'SHOPPING',
     6: 'LEISURE',
     7: 'LEISURE',
     8: 'HOME',
     9: 'HOME',
     10: 'OTHER',
     11: 'HOME',
     31: 'SCHOOL',
     32: 'SCHOOL',
     99: 'NA'}},
   'KiD': {'trip_start_weekday': {0: 'MON',
     1: 'TUE',
     2: 'WED',
     3: 'THU',
     4: 'FRI',
     5: 'SAT',
     6: 'SUN'},
    'trip_purpose': {1: 'TRANSPORT',
     2: 'SERVICES',
     3: 'PEOPLE_MOBILITY',
     4: 'WORK',
     5: 'WORK',
     6: 'WORK',
     7: 'SCHOOL',
     8: 'SHOPPING',
     9: 'LEISURE',
     10: 'PEOPLE_MOBILITY',
     11: 'OTHER',
     12: 'HOME'},
    'vehicle_segment': {1: 'Light motorised vehicle',
     2: 'Car',
     3: 'Van',
     4: 'Truck',
     5: 'Tractor unit',
     6: 'Coach',
     7: 'City bus',
     8: 'Other tractor unit',
     9: 'Agriculture and forestry tractor unit',
     11: 'Other'}},
   'VF': {'trip_start_weekday': {1: 'MON',
     2: 'TUE',
     3: 'WED',
     4: 'THU',
     5: 'FRI',
     6: 'SAT',
     7: 'SUN'},
    'trip_purpose': {1: 'WORK',
     2: 'WORK',
     3: 'SCHOOL',
     4: 'SHOPPING',
     5: 'SHOPPING',
     6: 'LEISURE',
     7: 'LEISURE',
     8: 'HOME',
     9: 'HOME',
     10: 'OTHER',
     11: 'HOME',
     31: 'SCHOOL',
     32: 'SCHOOL',
     99: 'NA'},
    'vehicle_segment': {'klein': 'S',
     'kompakt': 'S',
     'mittel': 'M',
     'gross': 'L'}}}}}

## _DataParser_ class

Let's first run the class and see the outputs we get.

In [20]:
data = parse_data(configs=configs)
data.process()

Generic file parsing properties set up.
Starting to retrieve local data file from c:\Users\mior_fa\Documents\7_Work\vencopy\vencopy_internal\vencopy\vencopy\tutorials\data_sampling\MiD17.csv.
Finished loading 2124 rows of raw data of type .csv.
Running in debug mode.
Finished harmonization of variables.
Finished harmonization of ID variables.
Starting filtering, applying 8 filters.
All filters combined yielded that a total of 241 trips are taken into account.
This corresponds to 40.166666666666664 percent of the original data.
Completed park timestamp adjustments.
Finished activity composition with 240 trips and 240 parking activites.
Dataset written to c:\Users\mior_fa\Documents\7_Work\vencopy\vencopy_internal\vencopy\vencopy\output\dataparser\vencopy_output_dataparser_None_MiD17.csv.
Parsing MiD dataset completed.

,index,unique_id,park_id,trip_id,is_driver,household_person_id,trip_weight,trip_scale_factor,trip_purpose,trip_distance,...,timestamp_start,timestamp_end,is_first_activity,is_last_activity,activity_id,next_activity_id,previous_activity_id,is_first_trip,is_first_park_activity,time_delta
0,0,1410,0.0,NaN,True,1410,0.146627,39.299224,2,NaN,...,2017-03-13 00:00:00,2017-03-13 14:00:00,True,False,0.0,4.0,NaN,False,True,0 days 14:00:00
1,1,1410,NaN,4.0,True,1410,0.146627,39.299224,2,9.50,...,2017-03-13 14:00:00,2017-03-13 14:50:00,False,False,4.0,4.0,0.0,True,False,0 days 00:50:00
2,2,1410,4.0,NaN,True,1410,0.146627,39.299224,2,NaN,...,2017-03-13 14:50:00,2017-03-14 00:00:00,False,True,4.0,NaN,4.0,False,False,0 days 09:10:00
3,3,636,0.0,NaN,True,636,0.190006,50.925648,1,NaN,...,2016-07-24 00:00:00,2016-07-24 06:10:00,True,False,0.0,1.0,NaN,False,True,0 days 06:10:00
4,4,636,NaN,1.0,True,636,0.190006,50.925648,1,13.30,...,2016-07-24 06:10:00,2016-07-24 06:30:00,False,False,1.0,1.0,0.0,True,False,0 days 00:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,556,1840,0.0,NaN,True,1840,2.340718,627.363646,7,NaN,...,2017-03-27 00:00:00,2017-03-27 09:45:00,True,False,0.0,1.0,NaN,False,True,0 days 09:45:00
556,557,1840,NaN,1.0,True,1840,2.340718,627.363646,7,4.75,...,2017-03-27 09:45:00,2017-03-27 10:05:00,False,False,1.0,1.0,0.0,True,False,0 days 00:20:00
557,558,1840,1.0,NaN,True,1840,2.340718,627.363646,7,NaN,...,2017-03-27 10:05:00,2017-03-27 11:30:00,False,False,1.0,2.0,1.0,False,False,0 days 01:25:00
558,559,1840,NaN,2.0,True,1840,2.340718,627.363646,8,4.75,...,2017-03-27 11:30:00,2017-03-27 11:40:00,False,False,2.0,2.0,1.0,False,False,0 days 00:10:00
559,560,1840,2.0,NaN,True,1840,2.340718,627.363646,8,NaN,...,2017-03-27 11:40:00,2017-03-28 00:00:00,False,True,2.0,NaN,2.0,False,False,0 days 12:20:00

We can see from the print statements in the class that after reading in the initial dataset, which contained 2124 rows, and applying 8 filters, we end up with a database containing 1980 suitable entries, which corresponds to about 93% of the initial sample.
These trip respect the condition that they all need to be shorter than 1000km, which is set in the parseConfig under the 'filterDict' key.

Now we can, for example, change in the filters the maximum allowed trip distance from 1000km to 50km and see how this affects the resulting available trips (the extreme case of 50km is only used for the tutorial purpose).

In [21]:
configs['dev_config']['dataparsers']['filters'][datasetID]['smaller_than']['trip_distance'] = [50]

In [22]:
data = parse_data(configs=configs)
data.process()

Generic file parsing properties set up.
Starting to retrieve local data file from c:\Users\mior_fa\Documents\7_Work\vencopy\vencopy_internal\vencopy\vencopy\tutorials\data_sampling\MiD17.csv.
Finished loading 2124 rows of raw data of type .csv.
Running in debug mode.
Finished harmonization of variables.
Finished harmonization of ID variables.
Starting filtering, applying 8 filters.
All filters combined yielded that a total of 233 trips are taken into account.
This corresponds to 38.83333333333333 percent of the original data.
Completed park timestamp adjustments.
Finished activity composition with 232 trips and 232 parking activites.
Dataset written to c:\Users\mior_fa\Documents\7_Work\vencopy\vencopy_internal\vencopy\vencopy\output\dataparser\vencopy_output_dataparser_None_MiD17.csv.
Parsing MiD dataset completed.

,index,unique_id,park_id,trip_id,is_driver,household_person_id,trip_weight,trip_scale_factor,trip_purpose,trip_distance,...,timestamp_start,timestamp_end,is_first_activity,is_last_activity,activity_id,next_activity_id,previous_activity_id,is_first_trip,is_first_park_activity,time_delta
0,0,1410,0.0,NaN,True,1410,0.146627,39.299224,2,NaN,...,2017-03-13 00:00:00,2017-03-13 14:00:00,True,False,0.0,4.0,NaN,False,True,0 days 14:00:00
1,1,1410,NaN,4.0,True,1410,0.146627,39.299224,2,9.50,...,2017-03-13 14:00:00,2017-03-13 14:50:00,False,False,4.0,4.0,0.0,True,False,0 days 00:50:00
2,2,1410,4.0,NaN,True,1410,0.146627,39.299224,2,NaN,...,2017-03-13 14:50:00,2017-03-14 00:00:00,False,True,4.0,NaN,4.0,False,False,0 days 09:10:00
3,3,636,0.0,NaN,True,636,0.190006,50.925648,1,NaN,...,2016-07-24 00:00:00,2016-07-24 06:10:00,True,False,0.0,1.0,NaN,False,True,0 days 06:10:00
4,4,636,NaN,1.0,True,636,0.190006,50.925648,1,13.30,...,2016-07-24 06:10:00,2016-07-24 06:30:00,False,False,1.0,1.0,0.0,True,False,0 days 00:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,537,1840,0.0,NaN,True,1840,2.340718,627.363646,7,NaN,...,2017-03-27 00:00:00,2017-03-27 09:45:00,True,False,0.0,1.0,NaN,False,True,0 days 09:45:00
537,538,1840,NaN,1.0,True,1840,2.340718,627.363646,7,4.75,...,2017-03-27 09:45:00,2017-03-27 10:05:00,False,False,1.0,1.0,0.0,True,False,0 days 00:20:00
538,539,1840,1.0,NaN,True,1840,2.340718,627.363646,7,NaN,...,2017-03-27 10:05:00,2017-03-27 11:30:00,False,False,1.0,2.0,1.0,False,False,0 days 01:25:00
539,540,1840,NaN,2.0,True,1840,2.340718,627.363646,8,4.75,...,2017-03-27 11:30:00,2017-03-27 11:40:00,False,False,2.0,2.0,1.0,False,False,0 days 00:10:00
540,541,1840,2.0,NaN,True,1840,2.340718,627.363646,8,NaN,...,2017-03-27 11:40:00,2017-03-28 00:00:00,False,True,2.0,NaN,2.0,False,False,0 days 12:20:00

We can see how with a maximum trip distance of 1000km, all filters combined yielded a total of 1980 trips, which corresponds to about 93% of the original dataset. By changing this values to 50km, additional 82 trips have been excluded, resulting in 1898 trips (89% ofthe initial dataset).

## Next Steps

In the next tutorial, you will learn more in detail the internal workings of the FlexEstimator class and how to customise some settings.